package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Template1_HttpsGithubComKseniailinaTemplate1gitRefsHeadsMaster'
in the project with id = 'Template1', and delete the patch script.
*/
create(RelativeId("Template1"), GitVcsRoot({
    id("Template1_HttpsGithubComKseniailinaTemplate1gitRefsHeadsMaster")
    name = "https://github.com/kseniailina/Template1.git#refs/heads/master"
    url = "https://github.com/kseniailina/Template1.git"
    authMethod = password {
        userName = "kseniailina"
        password = "credentialsJSON:c68c2a12-d73e-4649-8e2d-0341264f765f"
    }
}))

